import {
  IIncident,
  IResource,
  IShelter,
  IAllocation,
  IAuditEvent,
  IAlert,
  IBroadcast,
} from '../models/types.js';

export const SEED_INCIDENTS: IIncident[] = [
  {
    id: 'INC-2026-8801',
    title: 'Flash Flood & Trapped Residents in Residential Sector 4',
    description: 'Rapidly rising water levels (>1.8m) submerging ground level. 28 citizens stranded on building rooftops.',
    category: 'FLOOD',
    severity: 'CRITICAL',
    status: 'REPORTED',
    latitude: 19.0820,
    longitude: 72.8820,
    reportedAt: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    peopleAffected: 120,
    peopleTrapped: 28,
    injured: 4,
    requiredResources: ['WATER_VESSEL', 'MEDICAL_UNIT'],
    assignedResources: [],
    source: 'Field Officer D. Miller (Unit 404)',
    photoUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5',
    aiAssessment: {
      priorityScore: 98,
      recommendedResourceTypes: ['WATER_VESSEL', 'HELICOPTER', 'MEDICAL_UNIT'],
      urgencyReasoning: 'Rapid water level rise poses immediate threat to stranded rooftop victims.',
      assessedAt: new Date().toISOString(),
    },
    eta: 15,
  },
  {
    id: 'INC-2026-8802',
    title: 'Major Hospital Emergency Generator Power Grid Failure',
    description: 'Main transformer exploded following storm surge. ICU life support running on backup battery reserve.',
    category: 'POWER_OUTAGE',
    severity: 'CRITICAL',
    status: 'DISPATCHED',
    latitude: 19.0650,
    longitude: 72.8680,
    reportedAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    peopleAffected: 450,
    peopleTrapped: 0,
    injured: 12,
    requiredResources: ['SUPPLY_CONVOY', 'MEDICAL_UNIT'],
    assignedResources: ['RES-102', 'RES-105'],
    source: 'Dr. Sarah Vance (Chief Medical Off.)',
    photoUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514',
    aiAssessment: {
      priorityScore: 96,
      recommendedResourceTypes: ['SUPPLY_CONVOY', 'MEDICAL_UNIT'],
      urgencyReasoning: 'Power failure jeopardizes ICU patient life support within 25 minutes.',
      assessedAt: new Date().toISOString(),
    },
    eta: 10,
  },
  {
    id: 'INC-2026-8803',
    title: 'Landslide Debris Blocking Highway 12 Emergency Corridor',
    description: 'Approx 150 tons of mud and boulder debris blocking both lanes of primary supply route.',
    category: 'LANDSLIDE',
    severity: 'HIGH',
    status: 'ON_SITE',
    latitude: 19.1100,
    longitude: 72.9100,
    reportedAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    peopleAffected: 200,
    peopleTrapped: 6,
    injured: 1,
    requiredResources: ['HEAVY_EQUIPMENT'],
    assignedResources: ['RES-104'],
    source: 'Highway Patrol Bravo',
    aiAssessment: {
      priorityScore: 84,
      recommendedResourceTypes: ['HEAVY_EQUIPMENT'],
      urgencyReasoning: 'Primary logistics corridor obstructed. Medevac transport rerouted.',
      assessedAt: new Date().toISOString(),
    },
    eta: 0,
  },
  {
    id: 'INC-2026-8804',
    title: 'Commercial Chemical Warehouse Structural Rupture',
    description: 'Structural column failure caused collapse onto ammonia pressure tank.',
    category: 'HAZMAT',
    severity: 'HIGH',
    status: 'REPORTED',
    latitude: 19.0420,
    longitude: 72.8450,
    reportedAt: new Date(Date.now() - 1000 * 60 * 78).toISOString(),
    peopleAffected: 80,
    peopleTrapped: 4,
    injured: 2,
    requiredResources: ['SEARCH_RESCUE'],
    assignedResources: [],
    source: 'Harbor Security Dispatch',
    aiAssessment: {
      priorityScore: 88,
      recommendedResourceTypes: ['SEARCH_RESCUE', 'MEDICAL_UNIT'],
      urgencyReasoning: 'Toxic plume moving towards residential sector.',
      assessedAt: new Date().toISOString(),
    },
    eta: 20,
  },
  {
    id: 'INC-2026-8805',
    title: 'Bridge Approach Washout & Stranded Transit Bus',
    description: 'North approach road collapsed into river. City bus trapped on intact span section.',
    category: 'STRUCTURAL_COLLAPSE',
    severity: 'MEDIUM',
    status: 'DISPATCHED',
    latitude: 19.0980,
    longitude: 72.8520,
    reportedAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    peopleAffected: 15,
    peopleTrapped: 15,
    injured: 0,
    requiredResources: ['SEARCH_RESCUE'],
    assignedResources: ['RES-101'],
    source: 'Citizen Reporter ID #9041',
    aiAssessment: {
      priorityScore: 72,
      recommendedResourceTypes: ['SEARCH_RESCUE'],
      urgencyReasoning: 'Passengers trapped on isolated span; bridge structure stable for now.',
      assessedAt: new Date().toISOString(),
    },
    eta: 12,
  },
];

export const SEED_RESOURCES: IResource[] = [
  {
    id: 'RES-101',
    name: 'Search & Rescue Squad Alpha-1',
    type: 'SEARCH_RESCUE',
    agency: 'National Disaster Response Force',
    latitude: 19.0950,
    longitude: 72.8550,
    status: 'EN_ROUTE',
    capacity: 12,
    currentAssignment: 'INC-2026-8805',
    destination: 'Riverside Causeway North Approach',
    eta: 12,
    fuelOrSupplyPct: 88,
    contactChannel: 'VHF CH-14 (Alpha)',
  },
  {
    id: 'RES-102',
    name: 'Medevac Rapid Response Unit 4',
    type: 'MEDICAL_UNIT',
    agency: 'Metro Trauma Corps',
    latitude: 19.0650,
    longitude: 72.8680,
    status: 'ON_SITE',
    capacity: 6,
    currentAssignment: 'INC-2026-8802',
    destination: 'Central Municipal Trauma Hospital',
    eta: 0,
    fuelOrSupplyPct: 75,
    contactChannel: 'VHF CH-09 (MedNet)',
  },
  {
    id: 'RES-103',
    name: 'Aero-Rescue Eagle Flight 1',
    type: 'HELICOPTER',
    agency: 'Coast Guard Aviation',
    latitude: 19.0880,
    longitude: 72.8650,
    status: 'AVAILABLE',
    capacity: 4,
    fuelOrSupplyPct: 100,
    contactChannel: 'AIR-TOWER 121.5',
  },
  {
    id: 'RES-104',
    name: 'Heavy Engineer Excavator Corps 2',
    type: 'HEAVY_EQUIPMENT',
    agency: 'Public Works Dept',
    latitude: 19.1100,
    longitude: 72.9100,
    status: 'ON_SITE',
    capacity: 2,
    currentAssignment: 'INC-2026-8803',
    destination: 'Highway 12 East Ridge',
    eta: 0,
    fuelOrSupplyPct: 62,
    contactChannel: 'TAC-CH-03',
  },
  {
    id: 'RES-105',
    name: 'Power & Fuel Supply Convoy 9',
    type: 'SUPPLY_CONVOY',
    agency: 'State Energy Logistics',
    latitude: 19.0700,
    longitude: 72.8720,
    status: 'EN_ROUTE',
    capacity: 50,
    currentAssignment: 'INC-2026-8802',
    destination: 'Central Municipal Trauma Hospital',
    eta: 10,
    fuelOrSupplyPct: 92,
    contactChannel: 'LOGISTICS-CH-01',
  },
  {
    id: 'RES-106',
    name: 'Flood Water Boat Squadron 3',
    type: 'WATER_VESSEL',
    agency: 'Naval Reserve Rescue',
    latitude: 19.0780,
    longitude: 72.8790,
    status: 'AVAILABLE',
    capacity: 20,
    fuelOrSupplyPct: 95,
    contactChannel: 'MARINE-CH-16',
  },
];

export const SEED_SHELTERS: IShelter[] = [
  {
    id: 'SHL-401',
    name: 'Metro Indoor Stadium Safe Zone',
    latitude: 19.0600,
    longitude: 72.8580,
    capacity: 1500,
    occupied: 1140,
    availableBeds: 360,
    foodSupply: 4.0,
    waterSupply: 5.5,
    medicalStaff: 18,
    status: 'OPEN',
    address: 'Stadium Complex, Sector 2',
    contactPhone: '+1 (800) 555-SHELTER-1',
  },
  {
    id: 'SHL-402',
    name: 'St. Jude High School Gymnasium',
    latitude: 19.0900,
    longitude: 72.8900,
    capacity: 600,
    occupied: 585,
    availableBeds: 15,
    foodSupply: 1.5,
    waterSupply: 2.0,
    medicalStaff: 6,
    status: 'OPEN',
    address: 'School Road, Kurla West',
    contactPhone: '+1 (800) 555-SHELTER-2',
  },
  {
    id: 'SHL-403',
    name: 'East Ridge Civic Center',
    latitude: 19.1150,
    longitude: 72.9250,
    capacity: 850,
    occupied: 320,
    availableBeds: 530,
    foodSupply: 6.0,
    waterSupply: 7.0,
    medicalStaff: 12,
    status: 'OPEN',
    address: 'Civic Plaza Blvd, East Hills',
    contactPhone: '+1 (800) 555-SHELTER-3',
  },
  {
    id: 'SHL-404',
    name: 'South Port Disaster Relief Center',
    latitude: 19.0300,
    longitude: 72.8380,
    capacity: 500,
    occupied: 110,
    availableBeds: 390,
    foodSupply: 8.5,
    waterSupply: 9.0,
    medicalStaff: 8,
    status: 'OPEN',
    address: 'Port Authority Maritime Hall',
    contactPhone: '+1 (800) 555-SHELTER-4',
  },
];

export const SEED_ALLOCATIONS: IAllocation[] = [
  {
    id: 'ALC-301',
    incidentId: 'INC-2026-8802',
    resourceId: 'RES-102',
    needType: 'MEDICAL_UNIT',
    priorityScore: 96,
    distance: 2.1,
    eta: 0,
    status: 'ACTIVE',
    reason: 'Nearest available Medevac unit with emergency life support capabilities',
    allocatedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'ALC-302',
    incidentId: 'INC-2026-8802',
    resourceId: 'RES-105',
    needType: 'SUPPLY_CONVOY',
    priorityScore: 96,
    distance: 3.4,
    eta: 10,
    status: 'ACTIVE',
    reason: 'Carries emergency industrial diesel power generator for ICU grid restoration',
    allocatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'ALC-303',
    incidentId: 'INC-2026-8803',
    resourceId: 'RES-104',
    needType: 'HEAVY_EQUIPMENT',
    priorityScore: 84,
    distance: 1.2,
    eta: 0,
    status: 'ACTIVE',
    reason: 'Heavy excavator nearest to highway landslide site',
    allocatedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: 'ALC-304',
    incidentId: 'INC-2026-8805',
    resourceId: 'RES-101',
    needType: 'SEARCH_RESCUE',
    priorityScore: 72,
    distance: 4.8,
    eta: 12,
    status: 'ACTIVE',
    reason: 'High-water rescue squad equipped with structural harness gear',
    allocatedAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
  },
];

export const SEED_ALERTS: IAlert[] = [
  {
    id: 'ALT-101',
    severity: 'CRITICAL',
    title: 'ICU Generator Backup Power Critical',
    message: 'Central Hospital generator fuel at 25%. Medevac units requested.',
    incidentId: 'INC-2026-8802',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'ALT-102',
    severity: 'HIGH',
    title: 'Flash Flood Water Level Rising',
    message: 'Kurla Creek level increased 0.4m in 15 minutes. High tide expected.',
    incidentId: 'INC-2026-8801',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'ALT-103',
    severity: 'HIGH',
    title: 'Highway 12 Corridor Blocked',
    message: 'Supply route to East Ridge obstructed by landslide debris.',
    incidentId: 'INC-2026-8803',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
  },
];

export const SEED_AUDIT_EVENTS: IAuditEvent[] = [
  {
    id: 'AUD-501',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    actor: 'EOC Command Center',
    action: 'SYSTEM_INITIALIZATION',
    description: 'Disaster telemetry network initialized for Metro Coastal Region.',
  },
  {
    id: 'AUD-502',
    timestamp: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    actor: 'Dr. Sarah Vance',
    action: 'INCIDENT_REPORTED',
    incidentId: 'INC-2026-8802',
    description: 'Hospital power outage reported at Central Municipal Trauma Hospital.',
  },
  {
    id: 'AUD-503',
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    actor: 'EOC Dispatch Officer',
    action: 'RESOURCE_DISPATCHED',
    incidentId: 'INC-2026-8802',
    resourceId: 'RES-102',
    description: 'Medevac unit RES-102 dispatched to incident INC-2026-8802.',
  },
];

export const SEED_BROADCASTS: IBroadcast[] = [
  {
    id: 'BRD-901',
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    priority: 'EMERGENCY',
    title: 'FLASH FLOOD ADVISORY - SECTORS 4 & 5',
    message: 'High tide combined with storm surge has breached Kurla Creek embankment. All low-lying residents must evacuate immediately to Metro Indoor Stadium Shelter (SHL-401).',
    targetArea: 'North Metro Coastal Zone',
    issuedBy: 'EOC Command Chief V. Thorne',
  },
  {
    id: 'BRD-902',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    priority: 'ADVISORY',
    title: 'HIGHWAY 12 TRAFFIC DIVERSION',
    message: 'Highway 12 East Ridge is blocked due to landslide debris. Emergency transport vehicles must use Eastern Bypass Route B.',
    targetArea: 'Eastern Foothills Sector',
    issuedBy: 'Logistics Control',
  },
];
